TT09: updated .github/workflow, config.tcl -> config.json, changed folder structure.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,39 +1,47 @@
 name: test
-# either manually started, or on a schedule
-on: [ push, workflow_dispatch ]
+on: [push, workflow_dispatch]
 jobs:
   test:
-    # ubuntu
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
-    # need the repo checked out
-    - name: checkout repo
-      uses: actions/checkout@v3
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
 
-    # install oss fpga tools
-    - name: install oss-cad-suite
-      uses: YosysHQ/setup-oss-cad-suite@v2
-      with:
-          python-override: true
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-    - run: | 
-        yosys --version
-        iverilog -V
-        cocotb-config --libpython
-        cocotb-config --python-bin
+      - name: Install iverilog
+        shell: bash
+        run: sudo apt-get update && sudo apt-get install -y iverilog
 
-    - name: test
-      run: |
-        cd src
-        make clean
-        make
-        # make will return success even if the test fails, so check for failure in the results.xml
-        ! grep failure results.xml
+      # Set Python up and install cocotb
+      - name: Setup python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
 
-    - name: upload vcd
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
+      - name: Install Python packages
+        shell: bash
+        run: pip install -r test/requirements.txt
+
+      - name: Run tests
+        run: |
+          cd test
+          make clean
+          make
+          # make will return success even if the test fails, so check for failure in the results.xml
+          ! grep failure results.xml
+
+      - name: Test Summary
+        uses: test-summary/action@v2.3
+        with:
+          paths: "test/results.xml"
+        if: always()
+
+      - name: upload vcd
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
           name: test-vcd
-          path: src/tb.vcd
-
+          path: |
+            test/tb.vcd
+            test/results.xml
